@startuml
actor Caller as caller
participant GenerateMapActor as gmActor
participant knowledge
participant workerActor

caller -> gmActor ** : create
gmActor -> gmActor ++ : start()
gmActor -> knowledgeBaseResponseAdapter ** : create
deactivate gmActor

caller -> gmActor ++ : GenerateMapMessage
gmActor -> gmActor : onGenerateMap()
gmActor -> gmActor : retrieveMapTileMaterials()
gmActor -> knowledge ++ : KnowledgeBaseMessage.GetMessage
deactivate gmActor

knowledge -> knowledge : onGet()
knowledge -> knowledgeBaseResponseAdapter --++ : KnowledgeBaseMessage.ResponseMessage
knowledgeBaseResponseAdapter -> gmActor ++ : WrappedKnowledgeBaseResponse
gmActor -> gmActor : onWrappedKnowledgeBaseResponse

alt response == KnowledgeBaseMessage.ErrorMessage case
gmActor -> caller : ResponseErrorMessage
else response = KnowledgeBaseMessage.ReplyMessage case
gmActor -> gmActor -- : MaterialsLoadSuccessMessage
end

-> gmActor : MaterialsLoadSuccessMessage
activate gmActor
gmActor -> gmActor :  onMaterialsLoadSuccess()
gmActor -> workerActor ** : create
deactivate gmActor

@enduml
