/*
 * dwarfhustle-model-api - Manages the compile dependencies for the model.
 * Copyright © 2022-2024 Erwin Müller (erwin.mueller@anrisoftware.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.anrisoftware.dwarfhustle.model.api.objects

[
    [
        chunkSize: 2,
        chunksCount: 9,
        chunks:[
            [chunk: [0, 0, 0, 4, 4, 4],blocks:[],
                chunks:[
                    [chunk: [0, 0, 0, 2, 2, 2],
                        chunks: [],
                        blocks: [
                            0,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                        ]
                    ],
                    [chunk:[0, 0, 2, 2, 2, 4],
                        chunks: [],
                        blocks:[
                            0,
                            0,
                            2,
                            0,
                            0,
                            3,
                            0,
                            1,
                            2,
                            0,
                            1,
                            3,
                            1,
                            0,
                            2,
                            1,
                            0,
                            3,
                            1,
                            1,
                            2,
                            1,
                            1,
                            3
                        ]
                    ],
                    [chunk:[0, 2, 0, 2, 4, 2],
                        chunks: [],
                        blocks:[
                            0,
                            2,
                            0,
                            0,
                            2,
                            1,
                            0,
                            3,
                            0,
                            0,
                            3,
                            1,
                            1,
                            2,
                            0,
                            1,
                            2,
                            1,
                            1,
                            3,
                            0,
                            1,
                            3,
                            1
                        ]
                    ],
                    [chunk:[0, 2, 2, 2, 4, 4],
                        chunks: [],
                        blocks:[
                            0,
                            2,
                            2,
                            0,
                            2,
                            3,
                            0,
                            3,
                            2,
                            0,
                            3,
                            3,
                            1,
                            2,
                            2,
                            1,
                            2,
                            3,
                            1,
                            3,
                            2,
                            1,
                            3,
                            3
                        ]
                    ],
                    [chunk:[2, 0, 0, 4, 2, 2],
                        chunks: [],
                        blocks:[
                            2,
                            0,
                            0,
                            2,
                            0,
                            1,
                            2,
                            1,
                            0,
                            2,
                            1,
                            1,
                            3,
                            0,
                            0,
                            3,
                            0,
                            1,
                            3,
                            1,
                            0,
                            3,
                            1,
                            1
                        ]
                    ],
                    [chunk:[2, 0, 2, 4, 2, 4],
                        chunks: [],
                        blocks:[
                            2,
                            0,
                            2,
                            2,
                            0,
                            3,
                            2,
                            1,
                            2,
                            2,
                            1,
                            3,
                            3,
                            0,
                            2,
                            3,
                            0,
                            3,
                            3,
                            1,
                            2,
                            3,
                            1,
                            3
                        ]
                    ],
                    [chunk:[2, 2, 0, 4, 4, 2],
                        chunks: [],
                        blocks:[
                            2,
                            2,
                            0,
                            2,
                            2,
                            1,
                            2,
                            3,
                            0,
                            2,
                            3,
                            1,
                            3,
                            2,
                            0,
                            3,
                            2,
                            1,
                            3,
                            3,
                            0,
                            3,
                            3,
                            1
                        ]
                    ],
                    [chunk:[2, 2, 2, 4, 4, 4],
                        chunks: [],
                        blocks:[
                            2,
                            2,
                            2,
                            2,
                            2,
                            3,
                            2,
                            3,
                            2,
                            2,
                            3,
                            3,
                            3,
                            2,
                            2,
                            3,
                            2,
                            3,
                            3,
                            3,
                            2,
                            3,
                            3,
                            3
                        ],
                    ]
                ]
            ]
        ]
    ]
]
